version: '3.7'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: proffy
    volumes:
      - ./pgdata:/var/lib/postgres/data
    ports:
      - '5432:5432'
  api:
    build: .
    depends_on:
      - db
    ports:
      - '11111:3030'
